#################################################################
## Global
#################################################################
ansible_user_name: ansible

#################################################################
## Jupyter
#################################################################
jupyter_venv_path: /opt/jupyter-venv
jupyter_port: 8888

#################################################################
## Users
#################################################################
gpu_user: gpu

#################################################################
## Storage
#################################################################
shared_storage: /mnt/nfs/
shared_home_storage: /mnt/nfs/home

#################################################################
## Hugging Face Models
#################################################################
model_dir: /opt/llm
model_name: "mistralai/Mistral-7B-Instruct-v0.1"
local_model_dir: "/opt/llm/models/Mistral-7B-Instruct"
hf_token: "{{ lookup('env', 'HF_TOKEN') }}"
